### PR TITLE
Add support for CSS in the CLI. 

### PR DESCRIPTION
**Pull request by mamcx**

### CODE REVIEW

**Comment by lukaslueg** [comment]
Thanks for the PR. One nit and a failure in CI

**Comment by lukaslueg** [comment]
Could you address the nit mentioned above as well?

**Comment by mamcx** [comment]
> Could you address the nit mentioned above as well?

Which one? All the step passed...

**Comment by lukaslueg** [comment]
The review comment above. I fail to see why `read_css` should take an `Option<T>` just to pass through the `None`-case. The caller should filter `None`, probably something to the tune of `css.unwrap_or(DEFAULT_CSS)`.

**Comment by lukaslueg** [comment]
Thanks. I'll fix the clippy error myself. Would you care sharing the alternative css?

**Pull request merged**
